

CREATE TABLE Main (
  ID int(11) NOT NULL AUTO_INCREMENT,
  Name char(35) NOT NULL DEFAULT '',
  PRIMARY KEY (ID)
) ;


INSERT INTO Main VALUES (1,'A');
INSERT INTO Main VALUES (2,'B');
INSERT INTO Main VALUES (3,'C');


CREATE TABLE Sub (
  ID int(11) NOT NULL AUTO_INCREMENT,
  Name char(35) NOT NULL DEFAULT '',
  Main int(11) NOT NULL,
  PRIMARY KEY (ID)
  );
  
  
INSERT INTO Sub VALUES (1,'A1',1);
INSERT INTO Sub VALUES (2,'A2',1);
INSERT INTO Sub VALUES (3,'A3',1);
INSERT INTO Sub VALUES (4,'B1',2);
INSERT INTO Sub VALUES (5,'B2',2);
INSERT INTO Sub VALUES (6,'B3',2);
INSERT INTO Sub VALUES (7,'C1',3);
INSERT INTO Sub VALUES (8,'C2',3);
INSERT INTO Sub VALUES (9,'C3',3);


CREATE TABLE SubSub (
  ID int(11) NOT NULL AUTO_INCREMENT,
  Name char(35) NOT NULL DEFAULT '',
  Sub int(11) NOT NULL,
  PRIMARY KEY (ID)
  );
  
  
INSERT INTO SubSub VALUES (1,'A1A',1);
